

GET http://localhost:4004/odata/v4/catalog/Books

###

POST http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json

 {
      "ID": 5,
      "title": "Sham Kumar",
      "stock": 400
    }

###

PUT http://localhost:4004/odata/v4/catalog/Books(ID=5)
Content-Type: application/json

 {
      "title": "Prem Kumar",
      "stock": 400
    }


###

DELETE http://localhost:4004/odata/v4/catalog/Books(ID=5)

###

GET http://localhost:4004/browse/Suppliers

###

GET http://localhost:4004/browse/Customers


###

POST http://localhost:4004/browse/Suppliers
Content-Type: application/json

  {
      "id": 1006,
      "supplierAddress": "maharastra",
      "supplierName": "devender fadnavis"
    }

###

PATCH http://localhost:4004/browse/Customers(companyId=1006)
Content-Type: application/json

 {
      "companyHeadquarters": "Delhi NCR",
      "companyName": "Ruturaj Gaikwad"
    }

  //// Associations & Compositions //////////////////
###

Get http://localhost:4004/SalesOrderService/$metadata 

###

Get http://localhost:4004/SalesOrderService/SalesOrders

###

Get http://localhost:4004/SalesOrderService/SalesOrderItems

 

###

POST http://localhost:4004/SalesOrderService/SalesOrders HTTP/1.1
Content-Type: application/json

{

  "ID": "1",

  "description": "Order 1",

  "customerNo": "C1",

  "salesOrg":"US01"

}

 

###

Get http://localhost:4004/SalesOrderService/SalesOrders(ID='1')

 

###

PATCH http://localhost:4004/SalesOrderService/SalesOrders(ID='1') HTTP/1.1
Content-Type: application/json

{

  "description": "Test Description",

  "customerNo": "C1"

}

###

POST http://localhost:4004/SalesOrderService/SalesOrderItems HTTP/1.1
Content-Type: application/json

{

  "salesOrder_ID": "1",

  "item": 10,

  "material": "Pen",

  "quantity": 100

}

 

###

##Expand Entity to view child component

Get http://localhost:4004/SalesOrderService/SalesOrders?$expand=items,customer HTTP/1.1

 

###

##Deep Insert for entity with Compositions

##Deep Insert-Example 1

 

POST http://localhost:4004/SalesOrderService/SalesOrders HTTP/1.1
Content-Type: application/json

{

  "ID": "2",

  "description": "Order 2",

  "customerNo": "C1",

  "salesOrg":"IN01",

  "items": [

    {

      "item": 10,

      "material": "Laptop",

      "quantity": 100

    },

    {

      "item": 20,

      "material": "Printer",

      "quantity": 50

    },

    {

      "item": 30,

      "material": "Mobile",

      "quantity": 20

    }

  ]

}

 

###

##Deep Insert-Example 2

POST http://localhost:4004/SalesOrderService/Customers
Content-Type: application/json

{

 "customerNo": "C1",

"customerName": "Peter",

  "addresses": {

    "ID": 100,

    "city": "Chennai",

    "country": "IN",

    "contact_phonenumber": "123-456-78",

    "contact_email": "Peter@gmail.com"

  }

}

###

Get http://localhost:4004/SalesOrderService/Customers?$expand=addresses

 

###

Get http://localhost:4004/SalesOrderService/Addresses

 

###

##Notice SalesOrder and associated items will be deleted.

DELETE http://localhost:4004/SalesOrderService/SalesOrders(ID='1')

 

###

##Notice Customer and associated address will be deleted.

DELETE http://localhost:4004/SalesOrderService/Customers(customerNo='C1')


////// Custom Handler Implementation ////////////////


###
Get http://localhost:4004/odata/v4/catalog/SalesOrders


###
Get http://localhost:4004/odata/v4/catalog/SalesOrderItems


###
Get http://localhost:4004/odata/v4/catalog/SalesOrders?$expand=item

###
Get http://localhost:4004/odata/v4/catalog/SalesOrders(2)

###
PATCH http://localhost:4004/odata/v4/catalog/SalesOrders(1) HTTP/1.1
Content-Type: application/json

{
    "description": "Order4",
    "customerNo": "C1"
}

###
POST http://localhost:4004/odata/v4/catalog/SalesOrders HTTP/1.1
Content-Type: application/json

{
  "ID":4,
  "customerNo": "C4",
  "description": "Order4"
}

###
POST http://localhost:4004/odata/v4/catalog/SalesOrderItems
Content-Type: application/json

 {
      "item": 3,
      "material": "Zinc",
      "quantity": "250",
      "salesOrder_ID": 3
    }

    
###
GET http://localhost:4004/odata/v4/catalog/SalesOrderItems

###

Get http://localhost:4004/odata/v4/catalog/SalesOrders(2)


###
DELETE http://localhost:4004/odata/v4/catalog/SalesOrders(1)
